
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pagina web principal</title>
    <link rel="stylesheet" href="css/estilos.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav>
            <a href="http://localhost/tienda_virtual/index.php">inicio</a>
            <a href="#">portafolio</a>
            <a href="#">servicios</a>
            <a href="#">contacto</a>
            <a href="http://localhost/tienda_virtual/ingproducts.php">ingresar al sistema</a>
        </nav>
        <section class="textos-header">
            <div><img src="img/logotipo2.png" alt=""></div>
        </section>
        <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->

        <div class="wave" style="height: 150px; overflow: hidden;" ><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;"><path d="M0.00,49.98 C149.99,150.00 349.20,-49.98 500.00,49.98 L500.00,150.00 L0.00,150.00 Z" style="stroke: none; fill: #fff;"></path></svg></div>

    </header>
    <main>
        <section class="contendor sobre-nosotros">
            <h2 class="titulo">Nuestros productos</h2>
            <div class="contenedor-sobre-nosotros">
                <img src="img/ilustracion2.svg" alt="" class="imagen-about-us">
                <div class="contenedor-textos">
                    <h3><span>1</span>Los mejores productos</h3>
                     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam illum facere soluta cumque fuga laboriosam, </p>
                     <h3><span>2</span>Los mejores productos</h3>
                     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam illum facere soluta cumque fuga laboriosam, </p>                    
                </div>
            </div>            
        </section>
        <section class="portafolio">
            <div class="contenedor">
                <h2 class="titulo">Portafolio</h2>
                <div class="galeria-port">
                    <div class="imagen-port">
                        <img src="img/image1.jpg" alt="">
                        <div class="hover-galeria">
                            <img src="img/icono1.png" alt="">
                             <p> Papeleria</p>
                        </div>                     
                    </div>
                    <div class="imagen-port">
                        <img src="img/imagen2.png" alt="">
                        <div class="hover-galeria">
                            <img src="img/icono1.png" alt="">
                             <p> Aseo</p>
                        </div>                     
                    </div>
                    <div class="imagen-port">
                        <img src="img/imge3.jpg" alt="">
                        <div class="hover-galeria">
                            <img src="img/icono1.png" alt="">
                             <p> Cafeteria</p>
                        </div>                     
                    </div>
                    <div class="imagen-port">
                        <img src="img/imge4.jpg" alt="">
                        <div class="hover-galeria">
                            <img src="img/icono1.png" alt="">
                             <p> Piscina</p>
                        </div>                     
                    </div>
                    <div class="imagen-port">
                        <img src="img/imge5.jpg" alt="">
                        <div class="hover-galeria">
                            <img src="img/icono1.png" alt="">
                             <p> Nuestro trabajo</p>
                        </div>                     
                    </div>
                    <div class="imagen-port">
                        <img src="img/imge6.jpg" alt="">
                        <div class="hover-galeria">
                            <img src="img/icono1.png" alt="">
                             <p> Nuestros valores</p>
                        </div>                     
                    </div>
                    <div class="imagen-port">
                        <img src="img/imge7.jpg" alt="">
                        <div class="hover-galeria">
                            <img src="img/icono1.png" alt="">
                             <p>Jardineria</p>
                        </div>                     
                    </div>
                    <div class="imagen-port">
                        <img src="img/image8.jpg" alt="">
                        <div class="hover-galeria">
                            <img src="img/icono1.png" alt="">
                             <p>Otros insumos</p>
                        </div>                     
                    </div>
                </div>
            </div>
        </section>
        <section class="clientes contenedor">
            <h2 class="titulo">Nuestros clientes</h2>
            <div class="cards">
                <div class="card">
                    <img src="img/face1.jpg" alt="">   
                    <div class="contenido-texto-card">
                        <h4>Name</h4>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium voluptate est animi ipsa atque architecto culpa facere quas optio illo mollitia nostrum amet, ratione ex officia? Iure non consequatur nisi.</p>
                    </div>
                </div>
                <div class="card">
                    <img src="img/face2.jpg" alt="">   
                    <div class="contenido-texto-card">
                        <h4>Name</h4>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium voluptate est animi ipsa atque architecto culpa facere quas optio illo mollitia nostrum amet, ratione ex officia? Iure non consequatur nisi.</p>
                    </div>
                </div>             
            </div>
        </section>
        <section class="about-services">
            <div class="contenedor">
                <h2 class="titulo">Nuestros servicios</h2>
                <div class="servicio-cont">
                    <div class="servicio-ind">
                        <img src="img/ilustracion1.svg" alt="">
                        <h3>Name</h3>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit eius corporis reiciendis praesentium nisi aperiam quo accusamus, impedit reprehenderit similique vero, excepturi consectetur? Accusantium ut ipsa mollitia impedit, fuga inventore.</p>
                    </div>
                    <div class="servicio-ind">
                        <img src="img/ilustracion3.svg" alt="">
                        <h3>Name</h3>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit eius corporis reiciendis praesentium nisi aperiam quo accusamus, impedit reprehenderit similique vero, excepturi consectetur? Accusantium ut ipsa mollitia impedit, fuga inventore.</p>
                    </div>
                    <div class="servicio-ind">
                        <img src="img/ilustracion4.svg" alt="">
                        <h3>Name</h3>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit eius corporis reiciendis praesentium nisi aperiam quo accusamus, impedit reprehenderit similique vero, excepturi consectetur? Accusantium ut ipsa mollitia impedit, fuga inventore.</p>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <footer>
       <div class="contenedor-footer">
            <div class="content-foo">
                <h4>phone</h4>
                <p>6356353</p>
            </div>
            <div class="content-foo">
                <h4>email</h4>
                <p>6356353</p>
            </div>
            <div class="content-foo">
                <h4>location</h4>
                <p>6356353</p>
            </div>
       </div>
       <h2 class="titulo-final">Copyright © Todos los derechos reservados</h2>
    </footer>
    
</body>
</html>