
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/estilos.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> 
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
    <title>tienda virtual</title>
<script>
  function limpiar()
  {
    document.getElementById("nombre_producto").value="";
    document.getElementById("marca").value="";
    document.getElementById("precio").value="";
    document.getElementById("descipcion").value="";
    document.getElementById("nombre_producto").focus();
  }
</script>
  
    
</head>
<body>   
<header>
        <nav>
        <a href="http://localhost/tienda_virtual/index.php">inicio</a>
            <a href="#">portafolio</a>
            <a href="#">servicios</a>
            <a href="#">contacto</a>
            <a href="http://localhost/tienda_virtual/ingproducts.php">ingresar al sistema</a>   
        </nav>
        <section class="textos-header">
            <div><img src="img/logotipo2.png" alt=""></div>
        </section>
        <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->

        <div class="wave" style="height: 150px; overflow: hidden;" ><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;"><path d="M0.00,49.98 C149.99,150.00 349.20,-49.98 500.00,49.98 L500.00,150.00 L0.00,150.00 Z" style="stroke: none; fill: #fff;"></path></svg></div>

 </header>
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" aria-disabled="true">Ingresar Productos</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
            <a class="nav-link" href="http://localhost/tienda_virtual/listadoUsuarios.php" tabindex="-1" >Eliminar y Editar productos</a>           
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
        </form>
        </div>
    </nav>
<main>

  <div style="height: 30px;">
      <div class="container ">
          <div class="row ">
              <div class="col-lg-12">
               <div class="card shadow-lg p-3 mb-5 bg-white ">
                 <div class="card-header">ADMINISTRACION DE PRODUCTOS</div>
                   <div class="card-body">

                      <form id="form1" action="procesar.php" method="post" >
                        <div class="form-row">
                              <div class="col-md-4 mb-3">
                                <label for="nombre_producto">Nombre del producto</label>
                                <input name="nombre_producto" id="nombre_producto" type="text" class="form-control" id="nombre_producto" placeholder="" value="" required>  
                              </div>
                              <div class="col-md-4 mb-3">
                                <label for="marca">marca del producto</label>
                                <input name="marca"  id="marca" type="text" class="form-control" id="marca" placeholder="" value="" required>
                              </div>                    
                         </div>
                          <div class="form-row ">
                              <div class="col-md-4 mb-3">
                                <label for="precio">precio del producto</label>
                                <input name="precio" type="number" class="form-control" id="precio" placeholder="" required>
                              </div>
                            </div>
                          </div>
                          <div class="form-group container" >
                              <div class=form-row >
                                <label for="exampleFormControlTextarea1">Descripcion</label>
                                <textarea class="form-control"  name="descripcion" id="exampleFormControlTextarea1" rows="3" required></textarea>
                              </div>
                          </div>
                          <div class="form-group container" >
                              <div class=form-row >
                                <label for="exampleFormControlTextarea1">foto</label>
                                <input name="foto" type="text" class="form-control" id="precio" placeholder="url fotografia" required>                                
                              </div>
                          </div>
                          <div class="container">
                            <button class="btn btn-primary" type="submit" name="btnenviar">Enviar</button>
                            <button class="btn btn-primary" type="button"  name="btnlimpiar" onclick="limpiar();" id="btnlimpiar" >limpiar</button>
                          </div>
                      </form>
                  </div> 
                </div> 
             </div>   
          </div>
        </div>       
      </div>                  
  </div>
</main>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>