<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>listado</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="css/estilos.css">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet"><link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
</head>
<body>

    <header>
        <nav>
        <a href="http://localhost/tienda_virtual/index.php">inicio</a>
            <a href="#">portafolio</a>
            <a href="#">servicios</a>
            <a href="#">contacto</a>
            <a href="http://localhost/tienda_virtual/ingproducts.php">ingresar al sistema</a>  
        </nav>
        <section class="textos-header">
            <div><img src="img/logotipo2.png" alt=""></div>
        </section>
        <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->

        <div class="wave" style="height: 150px; overflow: hidden;" ><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;"><path d="M0.00,49.98 C149.99,150.00 349.20,-49.98 500.00,49.98 L500.00,150.00 L0.00,150.00 Z" style="stroke: none; fill: #fff;"></path></svg></div>

    </header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" aria-disabled="true">Eliminar y Editar productos</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
            <a class="nav-link" href="http://localhost/tienda_virtual/ingproducts.php" tabindex="-1" >Ingresar productos</a>           
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
        </form>
        </div>
    </nav>

<main>
    <?php
        include("Basedatos.php");

        //1 crear una copia de la clase que acabe de traer
        $transaccion = new Basedatos();

        //2 crear la consulta para buscar datos
        $consultaSQL='SELECT * FROM productos WHERE 1';

        //utilizar el metodo consultar datos
        $productos=$transaccion->consultarDatos($consultaSQL);

            print_r($productos );
    ?>
    <div class="container">
        <div class="row row-cols-1 row-cols-md-3">

                <?php foreach($productos as $producto): ?>

                    <div class="col mb-4">

                        <div class="card h-100">
                         <img src="<?php echo($producto["foto"])?>" class="card-img-top" alt="foto">
                            <div class="card-body">
                                <h6 class="card-title"><?php echo($producto['NombreProducto']) ?> </h6>
                                <h7 class="card-title"><?php echo($producto['PrecioProducto']) ?> </h7>
                                <p class="card-text"><?php echo($producto['MarcaProducto']) ?> </p>
                                <p class="card-text"><?php echo($producto['Descripcion']) ?> </p>       
                                <a href="eliminarProductos.php?id= <?php echo($producto["CodigoProducto"]) ?>" class="btn btn-danger">Eliminar</a>                              
                                <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#editar<?php echo($producto["CodigoProducto"])?>">
                                        Editar
                                </button>
                            </div>
                        </div>

                        <div class="modal fade" id="editar<?php echo($producto["CodigoProducto"])?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Edicion de Usuario</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <form action="editarPro.php?id=<?php echo($producto["CodigoProducto"])?>" method="POST">
                                            <div class="form-group">
                                            <label>Nombre producto</label>
                                            <input type="text" class="form-control" name="nombreEditar" value="<?php echo($producto['NombreProducto']) ?> ">
                                            </div>
                                            <div class="form-group">
                                            <label>precio producto</label>
                                            <input type="text" class="form-control" name="precioEditar"value="<?php echo($producto['PrecioProducto']) ?>">
                                            </div>
                                            <div class="form-group">
                                            <label>Marca producto</label>
                                            <input type="text" class="form-control"name="marcaEditar"value="<?php echo($producto['MarcaProducto'])?>">
                                            </div>
                                            <div class="form-group">
                                            <label>Descripcion</label>
                                            <textarea name="descripcionEditar" class="form-control" rows="3"><?php echo($producto['Descripcion']) ?></textarea>
                                            </div>
                                            <button type="submit" name="botonEditar" class="btn btn-info">Editar</button>                                         
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach ?>
        </div>
    </div>
</main>



<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script> 
</body>
</html>