<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://fonts.googleapis.com/css?family=Roboto+Slab:300,400" rel="stylesheet"> 
	<link rel="stylesheet" href="css/estilosTienda.css">
	<title>Watch Store</title>
</head>
<body>
    <header>
        <nav>
            <a href="http://localhost/tienda_virtual/index.php">inicio</a>
            <a href="#">portafolio</a>
            <a href="#">servicios</a>
            <a href="#">contacto</a>
            <a href="http://localhost/tienda_virtual/ingproducts.php">ingresar al sistema</a>
        </nav>
        <section class="textos-header">
            <div><img src="img/logotipo2.png" alt=""></div>
        </section>
        <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->

        <div class="wave" style="height: 150px; overflow: hidden;" ><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;"><path d="M0.00,49.98 C149.99,150.00 349.20,-49.98 500.00,49.98 L500.00,150.00 L0.00,150.00 Z" style="stroke: none; fill: #fff;"></path></svg></div>

    </header>
    <div class="contenedor">
		
		<main>
			<nav>
				<button class="btn-menu" data-pushbar-target="pushbar-menu"><i class="fas fa-bars"></i></button>
				<a href="#" class="banner" data-pushbar-target="pushbar-productos">Otros productos Exclusivos</a>
			</nav>
			<section class="productos">
				<figure>
					<img src="img/img1.jpg" alt="">
					<figcaption>
						<a href="#" data-pushbar-target="pushbar-carrito">
							<span>$1800</span>
							<span>Comprar</span>
						</a>
					</figcaption>
				</figure>
				<figure>
					<img src="img/img2.jpg" alt="">
					<figcaption>
						<a href="#" data-pushbar-target="pushbar-carrito">
							<span>$1800</span>
							<span>Comprar</span>
						</a>
					</figcaption>
				</figure>
				<figure>
					<img src="img/img3.jpg" alt="">
					<figcaption>
						<a href="#" data-pushbar-target="pushbar-carrito">
							<span>$1800</span>
							<span>Comprar</span>
						</a>
					</figcaption>
				</figure>
			</section>
		</main>

		<!-- Pushbars: Menu -->
		
		
		<!-- Pushbars: Carrito de Compras -->
		

		<!-- Pushbars: Productos -->
		

		<!-- Pushbars: Newsletter -->
		
	</div>

	<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</body>
</html>